---
title: '11'
author: "Yiliu Cao"
date: "2024-05-16"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
batter <- read.csv("Data/Batter Data/2023_Guerrerojr.csv")
pitcher <- read.csv("Data/Pitcher Data/2023_Gausman.csv")
data2023 <- read.csv("Data/all2023_updated.csv")
```

```{r}
glimpse(data2023)
```

# Analysis
```{r}
data2023$HALF.INNING <- with(data2023,
          paste(GAME_ID, INN_CT, BAT_HOME_ID))

data2023$RUNS.SCORED <- with(data2023, (BAT_DEST_ID > 3) +
  (RUN1_DEST_ID > 3) + (RUN2_DEST_ID > 3) + (RUN3_DEST_ID > 3))
```

```{r}
get.state <- function(runner1, runner2, runner3, outs){
  runners <- paste(runner1, runner2, runner3, sep="")
  paste(runners, outs)
}
RUNNER1 <- ifelse(as.character(data2023[,"BASE1_RUN_ID"])=="", 0, 1)
RUNNER2 <- ifelse(as.character(data2023[,"BASE2_RUN_ID"])=="", 0, 1)
RUNNER3 <- ifelse(as.character(data2023[,"BASE3_RUN_ID"])=="", 0, 1)
data2023$STATE <- get.state(RUNNER1, RUNNER2, RUNNER3,
                           data2023$OUTS_CT)
NRUNNER1 <- with(data2023, as.numeric(RUN1_DEST_ID==1 |
                          BAT_DEST_ID==1))
NRUNNER2 <- with(data2023, as.numeric(RUN1_DEST_ID==2 |
                 RUN2_DEST_ID==2 | BAT_DEST_ID==2))
NRUNNER3 <- with(data2023, as.numeric(RUN1_DEST_ID==3 |
                 RUN2_DEST_ID==3 | RUN3_DEST_ID==3 | BAT_DEST_ID==3))
NOUTS <- with(data2023, OUTS_CT + EVENT_OUTS_CT)
data2023$NEW.STATE <- get.state(NRUNNER1, NRUNNER2, NRUNNER3, NOUTS)
```

```{r}
data2023 <- subset(data2023, (STATE != NEW.STATE) | (RUNS.SCORED > 0))
library(plyr)
data.outs <- ddply(data2023, .(HALF.INNING), summarize,
                  Outs.Inning=sum(EVENT_OUTS_CT))
data2023 <- merge(data2023, data.outs)
data2023C <- subset(data2023, Outs.Inning == 3)
data2023C <- subset(data2023, BAT_EVENT_FL == TRUE)
library(car)
data2023C$NEW.STATE <- recode(data2023C$NEW.STATE,
              "c('000 3', '100 3', '010 3', '001 3',
                 '110 3', '101 3', '011 3', '111 3')='3'")
```

```{r}
T.matrix <- with(data2023C, table(STATE, NEW.STATE))
P.matrix <- prop.table(T.matrix, 1)
P.matrix <- rbind(P.matrix, c(rep(0, 24), 1))
```

```{r}
count.runners.outs <- function(s)
  sum(as.numeric(strsplit(s,"")[[1]]), na.rm=TRUE)
runners.outs <- sapply(dimnames(T.matrix)[[1]], count.runners.outs)[-25]
R <- outer(runners.outs + 1, runners.outs, FUN="-")
dimnames(R)[[1]] <- dimnames(T.matrix)[[1]][-25]
dimnames(R)[[2]] <- dimnames(T.matrix)[[1]][-25]
R <- cbind(R, rep(0, 24))

simulate.half.inning <- function(P, R, start=1){
   s <- start; path <- NULL; runs <- 0
   while(s < 25){
     s.new <- sample(1:25, 1, prob=P[s, ])
     path <- c(path, s.new)
     runs <- runs + R[s, s.new]
     s <- s.new
}
runs }

RUNS <- replicate(10000, simulate.half.inning(T.matrix, R))
```

```{r}
RUNS
```

```{r}
library(markovchain)
markovChain <- new("markovchain", states=states, transitionMatrix=P.matrix)
plot(markovChain,package="diagram")
```


```{r}
gausman %>% 
  group_by(pitch_type) %>% 
  summarise(n=n())
```

```{r}
gausman %>% 
  ggplot(aes(x=release_speed)) +
  geom_histogram()
```

```{r}
gausman %>% 
  ggplot(aes(x=release_pos_x)) +
  geom_histogram()
```

```{r}
gausman %>% 
  ggplot(aes(x=release_pos_y)) +
  geom_histogram()
```

```{r}
gausman %>% 
  ggplot(aes(x=release_pos_z)) +
  geom_histogram()
```
